# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "auth.AuthRequest" do
    optional :username, :string, 1
    optional :password, :string, 2
  end
  add_message "auth.AuthResponse" do
    optional :token, :string, 1
  end
end

module Auth
  AuthRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthRequest").msgclass
  AuthResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.AuthResponse").msgclass
end
